## WORLD
/gate/world/geometry/setXLength 100 cm
/gate/world/geometry/setYLength 100 cm
/gate/world/geometry/setZLength 100 cm
/gate/world/setMaterial Air


## SPECT PANEL
/gate/world/daughters/name SPECThead
/gate/world/daughters/insert box
/gate/SPECThead/geometry/setXLength  100.0 mm
/gate/SPECThead/geometry/setYLength   74.0 mm
/gate/SPECThead/geometry/setZLength  196.0 mm
/gate/SPECThead/placement/setTranslation  0. 245.25 0. mm
#/gate/SPECThead/placement/setRotationAxis 0 0 1
#/gate/SPECThead/placement/setRotationAngle 42.5 deg
/gate/SPECThead/setMaterial Lead
/gate/SPECThead/repeaters/insert ring
/gate/SPECThead/ring/setRepeatNumber 10
/gate/SPECThead/vis/forceWireframe

#/gate/SPECThead/moves/insert 			rotation
#/gate/SPECThead/rotation/setSpeed		-0.05 deg/s
#/gate/SPECThead/rotation/setAxis		0 0 1


## CRYSTAL
/gate/SPECThead/daughters/name crystal
/gate/SPECThead/daughters/insert box
/gate/crystal/geometry/setXLength   80.0 mm
/gate/crystal/geometry/setYLength   40.0 mm
/gate/crystal/geometry/setZLength  176.0 mm
/gate/crystal/placement/setTranslation  0.0 7.0 0. mm
/gate/crystal/setMaterial CZT
/gate/crystal/vis/setColor yellow
/gate/crystal/vis/forceWireframe


## PIXEL
/gate/crystal/daughters/name pixel
/gate/crystal/daughters/insert box
/gate/pixel/geometry/setXLength   1.0 mm
/gate/pixel/geometry/setYLength   40.0 mm # 0.5 mm
/gate/pixel/geometry/setZLength   1.0 mm
/gate/pixel/placement/setTranslation  0.0 0.0 0.0 mm
/gate/pixel/setMaterial CZT
/gate/pixel/vis/setColor yellow
/gate/pixel/vis/forceWireframe

/gate/pixel/repeaters/insert cubicArray
/gate/pixel/cubicArray/setRepeatNumberX 80
/gate/pixel/cubicArray/setRepeatNumberY 1 #40
/gate/pixel/cubicArray/setRepeatNumberZ 176
/gate/pixel/cubicArray/setRepeatVector 1.0  1.0  1.0 mm
/gate/pixel/vis/setVisible false


## COLLIMATOR
/gate/SPECThead/daughters/name collimator
/gate/SPECThead/daughters/insert box
/gate/collimator/geometry/setXLength  80.0 mm
/gate/collimator/geometry/setYLength  24.0 mm
/gate/collimator/geometry/setZLength 176.0 mm
/gate/collimator/placement/setTranslation  0. -25. 0. mm
#/gate/collimator/setMaterial Air
/gate/collimator/setMaterial Tungsten
#/gate/collimator/setMaterial Tungsten_epoxy
/gate/collimator/vis/setColor red
/gate/collimator/vis/forceWireframe

/gate/collimator/daughters/name hole
/gate/collimator/daughters/insert box
/gate/hole/geometry/setXLength  1.28 mm #0.7 mm
/gate/hole/geometry/setYLength 24.00 mm
/gate/hole/geometry/setZLength  1.28 mm #0.7 mm
/gate/hole/setMaterial Air
/gate/hole/vis/setColor gray
/gate/hole/vis/setVisible false
/gate/hole/vis/forceWireframe

/gate/hole/repeaters/insert cubicArray
/gate/hole/cubicArray/setRepeatNumberX 50 #80
/gate/hole/cubicArray/setRepeatNumberY 1
/gate/hole/cubicArray/setRepeatNumberZ 110 #176
/gate/hole/cubicArray/setRepeatVector 1.6  0.0  1.6 mm

#/gate/systems/SPECThead/base/attach SPECThead
/gate/systems/SPECThead/crystal/attach crystal
/gate/systems/SPECThead/pixel/attach pixel

/gate/crystal/attachCrystalSD
/gate/pixel/attachCrystalSD

/gate/collimator/attachPhantomSD
/gate/hole/attachPhantomSD
#/gate/SPECThead/attachPhantomSD

/gate/systems/SPECThead/describe

