#=====================================================
# SOURCE
#=====================================================
/gate/source/addSource source
/gate/source/source/gps/particle   gamma
/gate/source/source/gps/energy     140.0 keV
/gate/source/source/gps/ang/type   iso

#/gate/source/source/gps/direction 1 0 0
#/gate/source/source/gps/ang/mintheta 0. deg
#/gate/source/source/gps/ang/maxtheta 17. deg
#/gate/source/source/gps/ang/minphi 0. deg
#/gate/source/source/gps/ang/maxphi 360. deg

/gate/source/source/setActivity    10000. Bq
/gate/source/source/setIntensity   1

/gate/source/source/gps/pos/centre 30. 20. 0. cm

