#=====================================================
# SOURCE
#=====================================================
/gate/source/addSource point1

/gate/source/point1/gps/particle gamma
/gate/source/point1/gps/ene/type Mono
#/gate/source/point1/gps/ene/mono 141.0 keV    #Tc-99m
/gate/source/point1/gps/ene/mono 218.0 keV   #Fr-221
#/gate/source/point1/gps/ene/mono 269.0 keV   #Ra-223
#/gate/source/point1/gps/ene/mono 365.0 keV   #I-131
#/gate/source/point1/gps/ene/mono 440.0 keV   #Bi-213
#/gate/source/point1/gps/ene/mono 910.0 keV   #Zr-89
/gate/source/point1/setActivity 10000. Bq
/gate/source/point1/gps/ang/type iso

/gate/source/point1/gps/type Volume
/gate/source/point1/gps/shape Sphere
/gate/source/point1/gps/radius 0.5 mm #0.1 mm
/gate/source/point1/gps/centre -15.0 125. 0. mm

/gate/source/point1/visualize 10 green 3

/gate/source/addSource point2

/gate/source/point2/gps/particle gamma
/gate/source/point2/gps/ene/type Mono
#/gate/source/point2/gps/ene/mono 141.0 keV    #Tc-99m
/gate/source/point2/gps/ene/mono 218.0 keV    #Fr-221
#/gate/source/point2/gps/ene/mono 269.0 keV    #Ra-223
#/gate/source/point2/gps/ene/mono 365.0 keV    #I-131
#/gate/source/point2/gps/ene/mono 440.0 keV   #Bi-213
#/gate/source/point2/gps/ene/mono 910.0 keV   #Zr-89
/gate/source/point2/setActivity 10000. Bq
/gate/source/point2/gps/ang/type iso

/gate/source/point2/gps/type Volume
/gate/source/point2/gps/shape Sphere
/gate/source/point2/gps/radius 0.5 mm #0.1 mm
/gate/source/point2/gps/centre 15.0 125. 0. mm

/gate/source/point2/visualize 10 green 3


/gate/source/list