#       P H A N T O M   G E O M E T R Y
/gate/world/daughters/name NEMA_IQ
/gate/world/daughters/insert box
/gate/NEMA_IQ/placement/setTranslation 0.0 0.0 0.0 cm
/gate/NEMA_IQ/geometry/setXLength 30. cm
/gate/NEMA_IQ/geometry/setYLength 23. cm
/gate/NEMA_IQ/geometry/setZLength 1. mm
/gate/NEMA_IQ/setMaterial Air
/gate/NEMA_IQ/vis/forceWireframe
/gate/NEMA_IQ/vis/setColor gray

# Upper Half of Phantom
# Center Section of Upper Outer Shell
/gate/NEMA_IQ/daughters/name outershell1
/gate/NEMA_IQ/daughters/insert cylinder
/gate/outershell1/placement/setTranslation 0.0 -3.5 0.0 cm
/gate/outershell1/geometry/setRmax 15. cm
/gate/outershell1/geometry/setHeight 1. mm
/gate/outershell1/geometry/setPhiStart 0. deg
/gate/outershell1/geometry/setDeltaPhi 180. deg
/gate/outershell1/setMaterial Plastic
/gate/outershell1/vis/forceWireframe
/gate/outershell1/vis/setColor red

# Water in Phantom
/gate/outershell1/daughters/name upperinterior
/gate/outershell1/daughters/insert cylinder
/gate/upperinterior/placement/setTranslation 0.0 0.0 0.0 cm
/gate/upperinterior/geometry/setRmax 14.7 cm
/gate/upperinterior/geometry/setRmin  0.0 cm
/gate/upperinterior/geometry/setHeight 1. mm
/gate/upperinterior/geometry/setPhiStart 0. deg
/gate/upperinterior/geometry/setDeltaPhi 180. deg
/gate/upperinterior/setMaterial Water
/gate/upperinterior/vis/forceWireframe
/gate/upperinterior/vis/setColor blue

# Plastic Shell Surrounding Center Cylinder
/gate/upperinterior/daughters/name centercyl
/gate/upperinterior/daughters/insert cylinder
/gate/centercyl/placement/setTranslation 0.0 3.5 0.0 cm
/gate/centercyl/geometry/setRmax 2.5 cm
/gate/centercyl/geometry/setHeight 1. mm
/gate/centercyl/setMaterial Plastic
/gate/centercyl/vis/forceWireframe
/gate/centercyl/vis/setColor red

# Hollow Space in Central Cylinder
/gate/centercyl/daughters/name centercylin
/gate/centercyl/daughters/insert cylinder
/gate/centercylin/placement/setTranslation 0.0 0.0 0.0 cm
/gate/centercylin/geometry/setRmax 2.1 cm
/gate/centercylin/geometry/setRmin 0.0 cm
/gate/centercylin/geometry/setHeight 1. mm
/gate/centercylin/setMaterial Air
#/gate/centercylin/vis/forceWireframe
/gate/centercylin/vis/setColor gray

# 10 mm Sphere Exterior
/gate/upperinterior/daughters/name sphere10
/gate/upperinterior/daughters/insert cylinder
/gate/sphere10/placement/setTranslation 2.86 8.45367 0.0 cm
/gate/sphere10/geometry/setRmax 0.6 cm
/gate/sphere10/geometry/setHeight 1. mm
/gate/sphere10/setMaterial Plastic
/gate/sphere10/vis/forceWireframe
/gate/sphere10/vis/setColor red

# 10 mm Sphere
/gate/sphere10/daughters/name sphere10in
/gate/sphere10/daughters/insert cylinder
/gate/sphere10in/placement/setTranslation 0.0 0.0 0.0 cm
/gate/sphere10in/geometry/setRmax 0.5 cm
/gate/sphere10in/geometry/setHeight 1. mm
/gate/sphere10in/setMaterial Air
#/gate/sphere10in/vis/forceWireframe
/gate/sphere10in/vis/setColor gray

# 13 mm Sphere Exterior
/gate/upperinterior/daughters/name sphere13
/gate/upperinterior/daughters/insert cylinder
/gate/sphere13/placement/setTranslation -2.86 8.45367 0.0 cm
/gate/sphere13/geometry/setRmax 0.75 cm
/gate/sphere13/geometry/setHeight 1. mm
/gate/sphere13/setMaterial Plastic
/gate/sphere13/vis/forceWireframe
/gate/sphere13/vis/setColor red

# 13 mm Sphere
/gate/sphere13/daughters/name sphere13in
/gate/sphere13/daughters/insert cylinder
/gate/sphere13in/placement/setTranslation 0.0 0.0 0.0 cm
/gate/sphere13in/geometry/setRmax 0.65 cm
/gate/sphere13in/geometry/setHeight 1. mm
/gate/sphere13in/setMaterial Air
#/gate/sphere13in/vis/forceWireframe
/gate/sphere13in/vis/setColor gray

# 17 mm Sphere Exterior
/gate/upperinterior/daughters/name sphere17
/gate/upperinterior/daughters/insert cylinder
/gate/sphere17/placement/setTranslation -5.72 3.5 0.0 cm
/gate/sphere17/geometry/setRmax 0.9 cm
/gate/sphere17/geometry/setHeight 1. mm
/gate/sphere17/setMaterial Plastic
/gate/sphere17/vis/forceWireframe
/gate/sphere17/vis/setColor red

# 17 mm Sphere
/gate/sphere17/daughters/name sphere17in
/gate/sphere17/daughters/insert cylinder
/gate/sphere17in/placement/setTranslation 0.0 0.0 0.0 cm
/gate/sphere17in/geometry/setRmax 0.85 cm
/gate/sphere17in/geometry/setHeight 1. mm
/gate/sphere17in/setMaterial Air
#/gate/sphere17in/vis/forceWireframe
/gate/sphere17in/vis/setColor gray

# 37 mm Sphere Exterior
/gate/upperinterior/daughters/name sphere37
/gate/upperinterior/daughters/insert cylinder
/gate/sphere37/placement/setTranslation 5.72 3.5 0.0 cm
/gate/sphere37/geometry/setRmax 1.95 cm
/gate/sphere37/geometry/setHeight 1. mm
/gate/sphere37/setMaterial Plastic
/gate/sphere37/vis/forceWireframe
/gate/sphere37/vis/setColor red

# 37 mm Sphere
/gate/sphere37/daughters/name sphere37in
/gate/sphere37/daughters/insert cylinder
/gate/sphere37in/placement/setTranslation 0.0 0.0 0.0 cm
/gate/sphere37in/geometry/setRmax 1.85 cm
/gate/sphere37in/geometry/setHeight 1. mm
/gate/sphere37in/setMaterial Air
#/gate/sphere37in/vis/forceWireframe
/gate/sphere37in/vis/setColor gray

# Lower Half Of Phantom
# Lower Left Corner Center Section Cylinder 
/gate/NEMA_IQ/daughters/name outershell2
/gate/NEMA_IQ/daughters/insert cylinder
/gate/outershell2/placement/setTranslation 7.0 -3.5 0.0 cm
/gate/outershell2/geometry/setRmax 8. cm
/gate/outershell2/geometry/setHeight 1. mm
/gate/outershell2/geometry/setPhiStart 270. deg
/gate/outershell2/geometry/setDeltaPhi  90. deg
/gate/outershell2/setMaterial Plastic
/gate/outershell2/vis/forceWireframe
/gate/outershell2/vis/setColor red

/gate/outershell2/daughters/name LLinterior
/gate/outershell2/daughters/insert cylinder
/gate/LLinterior/placement/setTranslation 0.0 0.0 0.0 cm
/gate/LLinterior/geometry/setRmax 7.7 cm
/gate/LLinterior/geometry/setRmin 0. cm
/gate/LLinterior/geometry/setHeight 1. mm
/gate/LLinterior/geometry/setPhiStart 270. deg
/gate/LLinterior/geometry/setDeltaPhi  90. deg
/gate/LLinterior/setMaterial Water
/gate/LLinterior/vis/forceWireframe
/gate/LLinterior/vis/setColor blue

# Lower Right Corner Center Section Cylinder 
/gate/NEMA_IQ/daughters/name outershell3
/gate/NEMA_IQ/daughters/insert cylinder
/gate/outershell3/placement/setTranslation -7.0 -3.5 0.0 cm
/gate/outershell3/geometry/setRmax 8. cm
/gate/outershell3/geometry/setHeight 1. mm
/gate/outershell3/geometry/setPhiStart 180. deg
/gate/outershell3/geometry/setDeltaPhi  90. deg
/gate/outershell3/setMaterial Plastic
/gate/outershell3/vis/forceWireframe
/gate/outershell3/vis/setColor red

/gate/outershell3/daughters/name LRinterior
/gate/outershell3/daughters/insert cylinder
/gate/LRinterior/placement/setTranslation 0.0 0.0 0.0 cm
/gate/LRinterior/geometry/setRmax 7.7 cm
/gate/LRinterior/geometry/setRmin 0. cm
/gate/LRinterior/geometry/setHeight 1. mm
/gate/LRinterior/geometry/setPhiStart 180. deg
/gate/LRinterior/geometry/setDeltaPhi  90. deg
/gate/LRinterior/setMaterial Water
/gate/LRinterior/vis/forceWireframe
/gate/LRinterior/vis/setColor blue

# Bottom Box
/gate/NEMA_IQ/daughters/name outershell4
/gate/NEMA_IQ/daughters/insert box
/gate/outershell4/placement/setTranslation 0.0 -7.5 0.0 cm
/gate/outershell4/geometry/setXLength 14. cm
/gate/outershell4/geometry/setYLength  8. cm
/gate/outershell4/geometry/setZLength 1. mm
/gate/outershell4/setMaterial Plastic
/gate/outershell4/vis/forceWireframe
/gate/outershell4/vis/setColor red

# Interior Box
/gate/outershell4/daughters/name boxinterior
/gate/outershell4/daughters/insert box
/gate/boxinterior/placement/setTranslation 0.0 0.15 0.0 cm
/gate/boxinterior/geometry/setXLength 14. cm
/gate/boxinterior/geometry/setYLength 7.7 cm
/gate/boxinterior/geometry/setZLength 1. mm
/gate/boxinterior/setMaterial Water
/gate/boxinterior/vis/forceWireframe
/gate/boxinterior/vis/setColor blue

# 22 mm Sphere Exterior
/gate/boxinterior/daughters/name sphere22
/gate/boxinterior/daughters/insert cylinder
/gate/sphere22/placement/setTranslation -2.86 2.39633 0.0 cm
/gate/sphere22/geometry/setRmax 1.2 cm
/gate/sphere22/geometry/setHeight 1. mm
/gate/sphere22/setMaterial Plastic
/gate/sphere22/vis/forceWireframe
/gate/sphere22/vis/setColor red

# 22 mm Sphere Interior
/gate/sphere22/daughters/name sphere22in
/gate/sphere22/daughters/insert cylinder
/gate/sphere22in/placement/setTranslation 0.0 0.0 0.0 cm
/gate/sphere22in/geometry/setRmax 1.1 cm
/gate/sphere22in/geometry/setHeight 1. mm
/gate/sphere22in/setMaterial Air
#/gate/sphere22in/vis/forceWireframe
/gate/sphere22in/vis/setColor gray

# 28 mm Sphere Exterior
/gate/boxinterior/daughters/name sphere28
/gate/boxinterior/daughters/insert cylinder
/gate/sphere28/placement/setTranslation 2.86 2.39633 0.0 cm
/gate/sphere28/geometry/setRmax 1.5 cm
/gate/sphere28/geometry/setHeight 1. mm
/gate/sphere28/setMaterial Plastic
/gate/sphere28/vis/forceWireframe
/gate/sphere28/vis/setColor red

# 28 mm Sphere
/gate/sphere28/daughters/name sphere28in
/gate/sphere28/daughters/insert cylinder
/gate/sphere28in/placement/setTranslation 0.0 0.0 0.0 cm
/gate/sphere28in/geometry/setRmax 1.4 cm
/gate/sphere28in/geometry/setHeight 1. mm
/gate/sphere28in/setMaterial Air
#/gate/sphere28in/vis/forceWireframe
/gate/sphere28in/vis/setColor gray


#      A t t a c h   P h a n t o m
/gate/NEMA_IQ/attachPhantomSD
/gate/upperinterior/attachPhantomSD
/gate/centercyl/attachPhantomSD
/gate/centercylin/attachPhantomSD
/gate/sphere10/attachPhantomSD
/gate/sphere10in/attachPhantomSD
/gate/sphere13/attachPhantomSD
/gate/sphere13in/attachPhantomSD
/gate/sphere17/attachPhantomSD
/gate/sphere17in/attachPhantomSD
/gate/sphere37/attachPhantomSD
/gate/sphere37in/attachPhantomSD
/gate/sphere22/attachPhantomSD
/gate/sphere22in/attachPhantomSD
/gate/sphere28/attachPhantomSD
/gate/sphere28in/attachPhantomSD
/gate/boxinterior/attachPhantomSD
/gate/LLinterior/attachPhantomSD
/gate/LRinterior/attachPhantomSD
/gate/outershell1/attachPhantomSD
/gate/outershell2/attachPhantomSD
/gate/outershell3/attachPhantomSD
/gate/outershell4/attachPhantomSD


